# This is a basic workflow to help you get started with Actions

name: Pandoc html

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: |
          mkdir build
          cp main.js build

      # Runs a single command using the runners shell
      - name: Build html
        uses: docker://pandoc/core:2.17
        with:
          # Use Readme.md as dummy input file (not used in the template)
          args: >-
            --metadata-file cv.yaml
            --template=template_cv.html
            -t html
            --output=build/cv.html
            README.md
      
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with:
          name: html
          path: |
            build/cv.html
            build/main.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Make sure we only deploy when pushed to master branch
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download html
        uses: actions/download-artifact@v3
        with:
          name: html
          path: public
      
      - run: mv public/cv.html public/index.html
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
