# This is a basic workflow to help you get started with Actions

name: Pandoc PDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-resume:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: mkdir build

      # Build the tex file using pandoc
      - name: Create tex file
        uses: docker://pandoc/core:2.17
        with:
          # Dummy REAMDE.md input file that is not used
          args: >-
            --metadata-file cv.yaml
            --template=template_resume.tex
            -t latex
            --output=build/resume.tex
            README.md
      
      # Compile the tex file using latex
      - name: Build tex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          working_directory: build
          latexmk_use_lualatex: true

      # Upload artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: build/resume.pdf

  build-cv:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - run: mkdir build

      # Build the tex file using pandoc
      - name: Create tex file
        uses: docker://pandoc/core:2.17
        with:
          # Dummy REAMDE.md input file that is not used
          args: >-
            --metadata-file cv.yaml
            --template=template_cv.tex
            -t latex
            --output=build/cv.tex
            README.md
      
      # Compile the tex file using latex
      - name: Build tex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          working_directory: build
          latexmk_use_lualatex: true

      # Upload artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: build/cv.pdf


  build-publication-list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: mkdir build

      # Build the tex file using pandoc
      - name: Create tex file
        uses: docker://pandoc/core:2.17
        with:
          # Dummy REAMDE.md input file that is not used
          args: >-
            --metadata-file cv.yaml
            --template=template_publication_list.tex
            -t latex
            --output=build/publication_list.tex
            README.md
      
      # Compile the tex file using latex
      - name: Build tex to pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: publication_list.tex
          working_directory: build
          latexmk_use_lualatex: true

      # Upload artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: publication list pdf
          path: build/publication_list.pdf
